---
builds:
  - binary: github-comment
    main: cmd/github-comment/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
release:
  prerelease: true
