image: alpine:3.16

variables:
  GITLAB_COMMENT_VERSION: "0.2.0"

.setup_tools: &setup_tools |
  apk add --upgrade curl tar
  curl -sSfL https://github.com/yuyaban/gitlab-comment/releases/download/v${GITLAB_COMMENT_VERSION}/gitlab-comment_${GITLAB_COMMENT_VERSION}_linux_amd64.tar.gz -o gitlab-comment_${GITLAB_COMMENT_VERSION}_linux_amd64.tar.gz
  tar zxvf gitlab-comment_${GITLAB_COMMENT_VERSION}_linux_amd64.tar.gz

post_note:
  before_script:
    - *setup_tools
  script:
    - ./gitlab-comment post -k hello -var target:"${CI_JOB_NAME}"
  rules:
    - when: manual

exec_note:
  before_script:
    - *setup_tools
  script:
    - ./gitlab-comment exec -k hello -var target:"${CI_JOB_NAME}" -- echo "test comment."
  rules:
    - when: manual
