---
name: CI
permissions: {}
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  AQUA_POLICY_CONFIG: ${{ github.workspace }}/aqua-policy.yaml
jobs:
  test:
    uses: suzuki-shunsuke/go-test-workflow/.github/workflows/test.yaml@e63ffd2de162e7a38c0f1b3ccaba92f9425edb6e # v0.1.0
    permissions:
      pull-requests: write
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: "1.19.5"

      - uses: aquaproj/aqua-installer@61e2563dfe7674cbf74fe6ec212e444198a3bb00 # v2.0.2
        with:
          aqua_version: v1.31.0

      - name: dry run
        run: bash scripts/test-dry-run.sh
