---
name: test-release
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/test-release.yaml
      - .goreleaser.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3.1.0
      - uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: '1.19.1'

      - name: remove changes
        # Sometimes it is failed to release by goreleaser due to changes of go.sum
        run: git checkout -- .
        if: "! startsWith(github.ref, 'refs/tags/')"
      - name: fetch tags to release
        run: git fetch --tags
        if: "! startsWith(github.ref, 'refs/tags/')"
      - name: Unshallow
        run: git fetch --prune --unshallow
        if: "! startsWith(github.ref, 'refs/tags/')"
      - name: Run GoReleaser (skip publish)
        uses: goreleaser/goreleaser-action@8f67e590f2d095516493f017008adc464e63adb1 # v4.1.0
        if: "! startsWith(github.ref, 'refs/tags/')"
        with:
          version: latest
          args: release --rm-dist --snapshot
